// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
// ignore: depend_on_referenced_packages
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBA93CZj8j4LxKftQ9umDU4DtFWg--Wl7c',
    appId: '1:907316693586:web:707b9da65b597473a5ed8b',
    messagingSenderId: '907316693586',
    projectId: 'chaty-666cb',
    authDomain: 'chaty-666cb.firebaseapp.com',
    storageBucket: 'chaty-666cb.appspot.com',
    measurementId: 'G-2NY79CEJC1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBcWkZV7q_oDje1X6Op2j-ofkqPCaJ0pXw',
    appId: '1:907316693586:android:1679799025751223a5ed8b',
    messagingSenderId: '907316693586',
    projectId: 'chaty-666cb',
    storageBucket: 'chaty-666cb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDO09dMyojdwLKllZIxErbMyppj1F7H_hc',
    appId: '1:907316693586:ios:38380ec492cbc295a5ed8b',
    messagingSenderId: '907316693586',
    projectId: 'chaty-666cb',
    storageBucket: 'chaty-666cb.appspot.com',
    iosClientId:
        '907316693586-hh0d4tnuqlisl0k3lre88jdve5db3jnv.apps.googleusercontent.com',
    iosBundleId: 'com.example.khaled',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDO09dMyojdwLKllZIxErbMyppj1F7H_hc',
    appId: '1:907316693586:ios:aa6007b8e9e114b5a5ed8b',
    messagingSenderId: '907316693586',
    projectId: 'chaty-666cb',
    storageBucket: 'chaty-666cb.appspot.com',
    iosClientId:
        '907316693586-55iqr4je0m66uqrn7qc8qmuhmtej0mco.apps.googleusercontent.com',
    iosBundleId: 'com.example.khaled.RunnerTests',
  );
}
